### ISSUE TITLE
Socket commands reference

### ISSUE THREAD

**Issue by Milleo** [py3minepi/py3minepi#13]
Hello!

Is there any reference documentation or wiki about all the commands that we can send through the socket?

Thanks

**Comment by doismellburning** [comment]
Hello!

We've used, roughly:
- https://github.com/py3minepi/py3minepi/blob/master/mcpi_protocol_spec.txt (which is essentially unmodified from the original library)
- https://github.com/py3minepi/py3minepi#links - specifically http://www.stuffaboutcode.com/p/minecraft-api-reference.html

I think http://www.stuffaboutcode.com/p/minecraft-api-reference.html is probably going to be most helpful to you. How's that sound?

**Comment by Milleo** [comment]
Thanks! But I already read those documentation, but I mean the events that I can send throught the socket that connects to the Java (I think). Because I'm interessted to help the API development to have more features and actions to interact with Minecraft.

**Comment by doismellburning** [comment]
Np! 

If I understand you correctly, you're looking to _expand_ the API? I think what you're after is what I'd call "the Java-side implementation of the API"?

The closest I know to this is @martinohanlon's RaspberryJuice http://www.stuffaboutcode.com/2014/10/minecraft-raspberryjuice-and-canarymod.html

@bennuttall / @martinohanlon - wondering if you two might be able to help here?

**Comment by martinohanlon** [comment]
@Milleo if you are looking to take minecraft modding further you probably want to look at java modding of Minecraft via direct integration. 

The socket based api only exists on Minecraft: Pi edition. 

RaspberryJuice is a Minecraft mod written in Java which implements the same socket based api on the PC version of Minecraft.

This is a reasonable tutorial on how to get started writing server mods for the Bukkit / Spigot - http://wiki.bukkit.org/Plugin_Tutorial

**Comment by Milleo** [comment]
Thanks for all the support, guys! I found the reference I was looking for:
http://wiki.vg/Minecraft_Pi_Protocol

Like @doismellburning said, I'm interested in expand the API, but as I checked this wiki, it seens there's nothing more to develop, the protocol seens to accept very few commands.

But this API is been used not only for Minecraft PI, but some local minecraft servers that's why I was so confused about it.

Anyway, thanks for all the support and sorry for those confuse mesages hehe

**Comment by martinohanlon** [comment]
@Milleo if you are interested in expanding the API, while this cant be achieved on Minecraft: Pi Edition (as its closed source), you can expand RaspberryJuice https://github.com/zhuowei/RaspberryJuice to deliver additions functions. I have already done this to support functions like player.getOrientation()

**Comment by Milleo** [comment]
@martinohanlon Cool! Already starred, I will study this bukkit server (I never instaled a Minecraft server, I know, it's a shame) and the Java library! Thanks for this tip, this project seens to be awesome.
